!*****************************************************************************
!
! Tutorial: How to ALPSize your applications
!
! Copyright (C) 2010-2013 by Synge Todo <wistaria@comp-phys.org>
!
! Permission is hereby granted, free of charge, to any person or organization
! obtaining a copy of the software and accompanying documentation covered by
! this license (the "Software") to use, reproduce, display, distribute,
! execute, and transmit the Software, and to prepare derivative works of the
! Software, and to permit third-parties to whom the Software is furnished to
! do so, all subject to the following:
!
! The copyright notices in the Software and this entire statement, including
! the above license grant, this restriction and the following disclaimer,
! must be included in all copies of the Software, in whole or in part, and
! all derivative works of the Software, unless such copies or derivative
! works are solely in the form of machine-executable object code generated by
! a source language processor.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
! FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
! SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
! FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
! ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
! DEALINGS IN THE SOFTWARE.
!
!****************************************************************************

! template for alpsizing a Fortran program

! subroutine alps_init
subroutine alps_init(caller)
  implicit none
  include "alps/fortran/alps_fortran.h"
  integer :: caller(2)

  return
end subroutine alps_init

! subroutine alps_run
subroutine alps_run(caller)
  implicit none
  include "alps/fortran/alps_fortran.h"
  integer :: caller(2)

  return
end subroutine alps_run

! alps_init_observables
subroutine alps_init_observables(caller)
  implicit none
  include "alps/fortran/alps_fortran.h"
  integer :: caller(2)

  return
end subroutine alps_init_observables

! alps_progerss
subroutine alps_progress(prgrs, caller)
  implicit none
  include "alps/fortran/alps_fortran.h"
  integer :: caller(2)
  real*8 :: prgrs

end subroutine alps_progress

! alps_is_thermalized
subroutine alps_is_thermalized(thrmlz, caller)
  implicit none
  include "alps/fortran/alps_fortran.h"
  integer :: caller(2)
  integer :: thrmlz

  return
end subroutine alps_is_thermalized

! alps_save
subroutine alps_save(caller)
  implicit none
  include "alps/fortran/alps_fortran.h"
  integer caller(2)

  return
end subroutine alps_save

! alps_load
subroutine alps_load(caller)
  implicit none
  include "alps/fortran/alps_fortran.h"
  integer :: caller(2)

  return
end subroutine alps_load

! alps_finalize
subroutine alps_finalize(caller)
  implicit none
  include "alps/fortran/alps_fortran.h"
  integer :: caller(2)

  return
end subroutine alps_finalize
