/*****************************************************************************
*
* Tutorial: How to ALPSize your applications
*
* Copyright (C) 2005-2013 by Synge Todo <wistaria@comp-phys.org>
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
* DEALINGS IN THE SOFTWARE.
*
*****************************************************************************/

#include <cmath>
#include <iostream>
#include <vector>
#include <boost/random.hpp>
#include <boost/timer.hpp>

#define L 128
#define T 1.0
#define MCSTEP (1 << 15)
#define MCTHRM (MCSTEP >> 3)
#define SEED 93812

inline int left(int x) {
  return x == 0 ? (L-1) : (x-1);
}

inline int right(int x) {
  return x == (L-1) ? 0 : (x+1);
}
  
int main() {

  // inverse temperature
  double beta = 1 / T;

  // random number generator
  boost::mt19937 eng(SEED);
  boost::variate_generator<boost::mt19937&, boost::uniform_real<> >
    random_01(eng, boost::uniform_real<>());

  // spin configuration
  std::vector<int> spins(L);
  for (int s = 0; s < L; ++s) spins[s] = (random_01() < 0.5 ? 1 : -1);

  // measurement
  double ene = 0;
  double mag = 0;
  double mag2 = 0;
  double mag4 = 0;

  // timer
  boost::timer tm;
  
  for (int mcs = 0; mcs < MCSTEP + MCTHRM; ++mcs) {
    for (int s = 0; s < L; ++s) {
      double diff = 2 * spins[s] * (spins[left(s)] + spins[right(s)]);
      if (random_01() < 0.5 * (1 + std::tanh(-0.5 * beta * diff))) spins[s] = -spins[s];
    }
    if (mcs >= MCTHRM) {
      double m = 0;
      double g = 0;
      for (int s = 0; s < L; ++s) {
        g -= spins[s] * spins[right(s)];
        m += spins[s];
      }
      g /= L;
      m /= L;
      ene += g;
      mag += m;
      mag2 += m * m;
      mag4 += std::pow(m, 4);
    }
  }

  // output results
  std::cout << "Energy = " << ene / MCSTEP << std::endl;
  std::cout << "Magnetization = " << mag / MCSTEP << std::endl;
  std::cout << "Magnetization^2 = " << mag2 / MCSTEP << std::endl;
  std::cout << "Magnetization^4 = " << mag4 / MCSTEP << std::endl;
  std::cout << "Binder Ratio of Magnetization = " << mag2 * mag2 / mag4 / MCSTEP << std::endl;
  std::cerr << "Elapsed time = " << tm.elapsed() << " sec\n";

  return 0;
}
